2020-07-14 14:25:46,838 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
2020-07-14 14:32:45,636 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
2020-07-14 14:49:22,244 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
2020-07-14 14:50:44,174 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
2020-07-14 14:52:18,872 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
2020-07-14 14:53:37,653 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
2020-07-14 14:54:14,460 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
2020-07-14 14:56:55,324 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
2020-07-14 15:03:01,407 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
2020-07-14 15:03:50,758 ERROR: Exception on /explore [GET] [in /usr/local/lib/python3.7/dist-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/dist-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/mohamed/Documents/web/flask/microblog/app/routes.py", line 146, in explore
    return render_template('index.html', title='Explore', posts=posts)
  File "/usr/local/lib/python3.7/dist-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/usr/local/lib/python3.7/dist-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.7/dist-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.7/dist-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.7/dist-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/mohamed/Documents/web/flask/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/mohamed/Documents/web/flask/microblog/app/templates/base.html", line 38, in top-level template code
    {% block contents %}
  File "/home/mohamed/Documents/web/flask/microblog/app/templates/index.html", line 47, in block "contents"
    {% include '_post.html' %}
  File "/home/mohamed/Documents/web/flask/microblog/app/templates/_post.html", line 4, in top-level template code
    <img src="{{ post.author.avatar(36) }}">
jinja2.exceptions.UndefinedError: 'None' has no attribute 'avatar'
2020-07-14 15:04:49,956 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
2020-07-14 15:05:29,306 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
2020-07-14 15:10:26,496 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
2020-07-14 15:13:07,210 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
2020-07-14 15:19:09,140 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
2020-07-14 15:28:01,012 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
2020-07-22 13:34:06,742 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
2020-07-22 13:34:17,115 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
2020-07-22 13:37:54,440 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
2020-07-22 13:43:01,295 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
2020-07-22 13:47:09,229 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
2020-07-22 13:50:53,496 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
2020-07-22 13:51:39,938 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
2020-07-22 13:59:04,123 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
2020-07-22 14:13:52,177 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
2020-07-22 14:14:09,939 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
2020-07-22 14:15:02,926 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
2020-07-22 14:28:53,804 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
2020-07-22 14:38:07,746 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
2020-07-22 14:38:14,219 ERROR: Exception on /home/user/pysec [GET] [in /usr/local/lib/python3.7/dist-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/dist-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/mohamed/Documents/web/flask/microblog/app/routes.py", line 84, in user
    return render_template('user.html', title=username, posts=posts, user=user, form=form)
  File "/usr/local/lib/python3.7/dist-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/usr/local/lib/python3.7/dist-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.7/dist-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.7/dist-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.7/dist-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/mohamed/Documents/web/flask/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/mohamed/Documents/web/flask/microblog/app/templates/base.html", line 39, in top-level template code
    {% block contents %}
  File "/home/mohamed/Documents/web/flask/microblog/app/templates/user.html", line 16, in block "contents"
    <p>{{ user.followers.count() }} followers, {{ user.followed.count() }} following.</p>
  File "/usr/local/lib/python3.7/dist-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'function object' has no attribute 'followers'
2020-07-22 14:39:02,898 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
