2020-07-05 10:09:39,952 ERROR: Exception on /login [GET] [in /usr/local/lib64/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib64/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mohamed/Documents/dev/web_dev/flask/microblog/app/routes.py", line 54, in login
    return render_template('login.html', form=form)
  File "/usr/local/lib64/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/usr/local/lib64/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/mohamed/Documents/dev/web_dev/flask/microblog/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/mohamed/Documents/dev/web_dev/flask/microblog/app/templates/base.html", line 35, in top-level template code
    {% block contents %}
  File "/home/mohamed/Documents/dev/web_dev/flask/microblog/app/templates/login.html", line 27, in block "contents"
    {{ form.submit(class_="required")() }}
TypeError: 'Markup' object is not callable
2020-07-05 10:10:05,666 INFO: Microblog startup [in /home/mohamed/Documents/dev/web_dev/flask/microblog/app/__init__.py:50]
2020-07-05 10:12:25,085 INFO: Microblog startup [in /home/mohamed/Documents/dev/web_dev/flask/microblog/app/__init__.py:50]
2020-07-05 10:12:45,949 INFO: Microblog startup [in /home/mohamed/Documents/dev/web_dev/flask/microblog/app/__init__.py:50]
2020-07-05 10:16:25,561 INFO: Microblog startup [in /home/mohamed/Documents/dev/web_dev/flask/microblog/app/__init__.py:50]
2020-07-05 10:17:22,700 INFO: Microblog startup [in /home/mohamed/Documents/dev/web_dev/flask/microblog/app/__init__.py:50]
2020-07-05 10:18:12,283 INFO: Microblog startup [in /home/mohamed/Documents/dev/web_dev/flask/microblog/app/__init__.py:50]
2020-07-05 10:19:39,475 INFO: Microblog startup [in /home/mohamed/Documents/dev/web_dev/flask/microblog/app/__init__.py:50]
2020-07-05 10:21:32,662 INFO: Microblog startup [in /home/mohamed/Documents/dev/web_dev/flask/microblog/app/__init__.py:50]
2020-07-05 10:22:47,100 INFO: Microblog startup [in /home/mohamed/Documents/dev/web_dev/flask/microblog/app/__init__.py:50]
2020-07-05 10:26:03,371 INFO: Microblog startup [in /home/mohamed/Documents/dev/web_dev/flask/microblog/app/__init__.py:50]
2020-07-05 10:32:17,316 INFO: Microblog startup [in /home/mohamed/Documents/dev/web_dev/flask/microblog/app/__init__.py:50]
2020-07-05 10:44:14,524 INFO: Microblog startup [in /home/mohamed/Documents/dev/web_dev/flask/microblog/app/__init__.py:50]
2020-07-05 10:44:57,395 INFO: Microblog startup [in /home/mohamed/Documents/dev/web_dev/flask/microblog/app/__init__.py:50]
2020-07-05 10:45:21,004 INFO: Microblog startup [in /home/mohamed/Documents/dev/web_dev/flask/microblog/app/__init__.py:50]
2020-07-05 10:49:08,127 INFO: Microblog startup [in /home/mohamed/Documents/dev/web_dev/flask/microblog/app/__init__.py:50]
2020-07-05 10:50:34,611 ERROR: Exception on /explore [GET] [in /usr/local/lib64/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib64/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mohamed/.local/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/mohamed/Documents/dev/web_dev/flask/microblog/app/routes.py", line 146, in explore
    return render_template('index.html', title='Explore', posts=posts)
  File "/usr/local/lib64/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/usr/local/lib64/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/mohamed/Documents/dev/web_dev/flask/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/mohamed/Documents/dev/web_dev/flask/microblog/app/templates/base.html", line 39, in top-level template code
    {% block contents %}
  File "/home/mohamed/Documents/dev/web_dev/flask/microblog/app/templates/index.html", line 33, in block "contents"
    {% include '_post.html' %}
  File "/home/mohamed/Documents/dev/web_dev/flask/microblog/app/templates/_post.html", line 4, in top-level template code
    <img src="{{ post.author.avatar(36) }}">
jinja2.exceptions.UndefinedError: 'None' has no attribute 'avatar'
