2020-07-22 14:39:09,401 ERROR: Exception on /home/user/pysec [GET] [in /usr/local/lib/python3.7/dist-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/dist-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/mohamed/Documents/web/flask/microblog/app/routes.py", line 84, in user
    return render_template('user.html', title=username, posts=posts, user=user, form=form)
  File "/usr/local/lib/python3.7/dist-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/usr/local/lib/python3.7/dist-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.7/dist-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.7/dist-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.7/dist-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/mohamed/Documents/web/flask/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/mohamed/Documents/web/flask/microblog/app/templates/base.html", line 39, in top-level template code
    {% block contents %}
  File "/home/mohamed/Documents/web/flask/microblog/app/templates/user.html", line 16, in block "contents"
    <p>{{ user.followers.count() }} followers, {{ user.followed.count() }} following.</p>
  File "/usr/local/lib/python3.7/dist-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'function object' has no attribute 'followers'
2020-07-22 14:40:44,806 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
2020-07-22 14:40:48,265 ERROR: Exception on /home/user/pysec [GET] [in /usr/local/lib/python3.7/dist-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/dist-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/mohamed/Documents/web/flask/microblog/app/routes.py", line 84, in user
    return render_template('user.html', title=username, posts=posts, user=user, form=form)
  File "/usr/local/lib/python3.7/dist-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/usr/local/lib/python3.7/dist-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.7/dist-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.7/dist-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.7/dist-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/mohamed/Documents/web/flask/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/mohamed/Documents/web/flask/microblog/app/templates/base.html", line 39, in top-level template code
    {% block contents %}
  File "/home/mohamed/Documents/web/flask/microblog/app/templates/user.html", line 16, in block "contents"
    <p>{{ user.followers().count() }} followers, {{ user.followed().count() }} following.</p>
jinja2.exceptions.UndefinedError: 'function object' has no attribute 'followers'
2020-07-22 14:41:29,268 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
2020-07-22 14:41:49,695 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
2020-07-22 14:43:41,807 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
2020-07-22 14:44:04,916 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
2020-07-22 14:45:48,914 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
2020-07-22 14:48:28,144 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
2020-07-22 14:49:52,414 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
2020-07-22 14:50:58,547 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:50]
